In [16]:
import numpy as np

In [17]:
import scipy.optimize as opt

In [18]:
c=np.array([2,3,4,1,5,3,2,2,1,1])
A=np.array([[1,0,1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1,0,1],[-1,-1,0,0,0,0,0,0,0,0],[0,0,-1,-1,0,0,0,0,0,0],[0,0,0,0,-1,-1,0,0,0,0],\
            [0,0,0,0,0,0,-1,-1,0,0],[0,0,0,0,0,0,0,0,-1,-1]])
b=np.array([1000,4000,-500,-900,-1800,-200,-700])

In [19]:
A,b,c

(array([[ 1,  0,  1,  0,  1,  0,  1,  0,  1,  0],
        [ 0,  1,  0,  1,  0,  1,  0,  1,  0,  1],
        [-1, -1,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0, -1, -1,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0, -1, -1,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0, -1, -1,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0, -1, -1]]),
 array([ 1000,  4000,  -500,  -900, -1800,  -200,  -700]),
 array([2, 3, 4, 1, 5, 3, 2, 2, 1, 1]))

In [20]:
res=opt.linprog(c,A_ub=A,b_ub=b,options={'disp':True})

Optimization terminated successfully.
         Current function value: 8400.000000 
         Iterations: 11


In [21]:
res

     fun: 8400.0
 message: 'Optimization terminated successfully.'
     nit: 11
   slack: array([  0., 900.,   0.,   0.,   0.,   0.,   0.])
  status: 0
 success: True
       x: array([ 500.,    0.,    0.,  900.,    0., 1800.,    0.,  200.,  500.,
        200.])

In [22]:
res.x

array([ 500.,    0.,    0.,  900.,    0., 1800.,    0.,  200.,  500.,
        200.])

**Por lo tanto, las respuestas son:**

$X_1=500$ cajas de cerveza Modelo para el bar 1.

$X_2=0$ cajas de cerveza Cuauhtémoc Moctezuma para el bar 1.

$X_3=0$ cajas de cerveza Modelo para el bar 2.

$X_4=900$ cajas de cerveza Cuauhtémoc Moctezuma para el bar 2.

$X_5=0$ cajas de cerveza Modelo para el bar 3.

$X_6=1800$ cajas de cerveza Cuauhtémoc Moctezuma para el bar 3.

$X_7=0$ cajas de cerveza Modelo para el bar 4.

$X_8=200$ cajas de cerveza Cuauhtémoc Moctezuma para el bar 4.

$X_9=500$ cajas de cerveza Modelo para el bar 5.

$X_10=200$ cajas de cerveza Cuauhtémoc Moctezuma para el bar 5.